package com.finance_tracker_rn

object WidgetCategoryIconMapper {
    private const val FALLBACK_ICON = android.R.drawable.ic_menu_help

    private val iconMap: Map<String, Int> = mapOf(
        "food" to android.R.drawable.ic_menu_crop,
        "food-fork-drink" to android.R.drawable.ic_menu_crop,
        "food-apple" to android.R.drawable.ic_menu_crop,
        "coffee" to android.R.drawable.ic_menu_crop,
        "cup" to android.R.drawable.ic_menu_crop,
        "beer" to android.R.drawable.ic_menu_crop,
        "wine" to android.R.drawable.ic_menu_crop,
        "pizza" to android.R.drawable.ic_menu_crop,
        "hamburger" to android.R.drawable.ic_menu_crop,
        "noodles" to android.R.drawable.ic_menu_crop,
        "cake" to android.R.drawable.ic_menu_crop,
        "ice-cream" to android.R.drawable.ic_menu_crop,
        "fish" to android.R.drawable.ic_menu_crop,
        "leaf" to android.R.drawable.ic_menu_crop,
        "car" to android.R.drawable.ic_menu_compass,
        "bus" to android.R.drawable.ic_menu_directions,
        "train" to android.R.drawable.ic_menu_directions,
        "subway-variant" to android.R.drawable.ic_menu_directions,
        "airplane" to android.R.drawable.ic_menu_compass,
        "taxi" to android.R.drawable.ic_menu_directions,
        "bicycle" to android.R.drawable.ic_menu_directions,
        "walk" to android.R.drawable.ic_menu_directions,
        "motorbike" to android.R.drawable.ic_menu_directions,
        "fuel" to android.R.drawable.ic_menu_compass,
        "parking" to android.R.drawable.ic_menu_mylocation,
        "ferry" to android.R.drawable.ic_menu_mapmode,
        "home" to android.R.drawable.ic_menu_view,
        "sofa" to android.R.drawable.ic_menu_view,
        "bed" to android.R.drawable.ic_menu_view,
        "shower" to android.R.drawable.ic_menu_view,
        "washing-machine" to android.R.drawable.ic_menu_manage,
        "lightbulb" to android.R.drawable.ic_menu_day,
        "water" to android.R.drawable.ic_menu_gallery,
        "fire" to android.R.drawable.ic_menu_compass,
        "tools" to android.R.drawable.ic_menu_manage,
        "broom" to android.R.drawable.ic_menu_manage,
        "television" to android.R.drawable.ic_menu_slideshow,
        "wifi" to android.R.drawable.ic_menu_share,
        "heart-pulse" to android.R.drawable.btn_star_big_on,
        "pill" to android.R.drawable.ic_menu_info_details,
        "hospital-box" to android.R.drawable.ic_menu_info_details,
        "stethoscope" to android.R.drawable.ic_menu_info_details,
        "tooth" to android.R.drawable.ic_menu_info_details,
        "eye" to android.R.drawable.ic_menu_view,
        "run" to android.R.drawable.ic_media_play,
        "weight-lifter" to android.R.drawable.ic_menu_sort_by_size,
        "yoga" to android.R.drawable.ic_menu_sort_by_size,
        "spa" to android.R.drawable.ic_menu_week,
        "needle" to android.R.drawable.ic_menu_edit,
        "bandage" to android.R.drawable.ic_menu_info_details,
        "cart" to android.R.drawable.ic_menu_add,
        "shopping" to android.R.drawable.ic_menu_agenda,
        "hanger" to android.R.drawable.ic_menu_agenda,
        "shoe-heel" to android.R.drawable.ic_menu_agenda,
        "tshirt-crew" to android.R.drawable.ic_menu_agenda,
        "watch" to android.R.drawable.ic_menu_recent_history,
        "sunglasses" to android.R.drawable.ic_menu_view,
        "gift" to android.R.drawable.ic_menu_share,
        "tag" to android.R.drawable.ic_menu_edit,
        "barcode-scan" to android.R.drawable.ic_menu_camera,
        "gamepad-variant" to android.R.drawable.ic_media_play,
        "movie-open" to android.R.drawable.ic_media_play,
        "music" to android.R.drawable.ic_media_play,
        "headphones" to android.R.drawable.ic_media_play,
        "theater" to android.R.drawable.ic_media_play,
        "ticket" to android.R.drawable.ic_menu_my_calendar,
        "bowling" to android.R.drawable.ic_menu_week,
        "basketball" to android.R.drawable.ic_menu_week,
        "soccer" to android.R.drawable.ic_menu_week,
        "tennis" to android.R.drawable.ic_menu_week,
        "cards-playing" to android.R.drawable.ic_menu_week,
        "book-open-variant" to android.R.drawable.ic_menu_info_details,
        "cash" to android.R.drawable.ic_menu_save,
        "credit-card" to android.R.drawable.ic_menu_save,
        "bank" to android.R.drawable.ic_lock_idle_lock,
        "chart-line" to android.R.drawable.ic_menu_sort_by_size,
        "chart-pie" to android.R.drawable.ic_menu_sort_by_size,
        "currency-usd" to android.R.drawable.ic_menu_save,
        "safe" to android.R.drawable.ic_lock_lock,
        "receipt" to android.R.drawable.ic_menu_edit,
        "wallet" to android.R.drawable.ic_menu_save,
        "hand-coin" to android.R.drawable.ic_menu_save,
        "briefcase" to android.R.drawable.ic_menu_manage,
        "laptop" to android.R.drawable.ic_menu_manage,
        "monitor" to android.R.drawable.ic_menu_manage,
        "printer" to android.R.drawable.ic_menu_edit,
        "phone" to android.R.drawable.ic_menu_call,
        "email" to android.R.drawable.ic_dialog_email,
        "calendar" to android.R.drawable.ic_menu_my_calendar,
        "pen" to android.R.drawable.ic_menu_edit,
        "paperclip" to android.R.drawable.ic_menu_edit,
        "account-tie" to android.R.drawable.ic_menu_myplaces,
        "account" to android.R.drawable.ic_menu_myplaces,
        "account-group" to android.R.drawable.ic_menu_myplaces,
        "baby-carriage" to android.R.drawable.ic_menu_myplaces,
        "dog" to android.R.drawable.ic_menu_myplaces,
        "cat" to android.R.drawable.ic_menu_myplaces,
        "school" to android.R.drawable.ic_menu_info_details,
        "human-male-female-child" to android.R.drawable.ic_menu_myplaces,
        "party-popper" to android.R.drawable.ic_menu_compass,
        "balloon" to android.R.drawable.ic_menu_compass,
        "cake-variant" to android.R.drawable.ic_menu_crop,
        "star" to android.R.drawable.btn_star_big_on,
        "flag" to android.R.drawable.ic_menu_mylocation,
        "map-marker" to android.R.drawable.ic_menu_mylocation,
        "cloud" to android.R.drawable.ic_menu_upload,
        "moon" to android.R.drawable.ic_menu_day,
        "sun-wireless" to android.R.drawable.ic_menu_day,
        "flower" to android.R.drawable.ic_menu_gallery,
        "recycle" to android.R.drawable.ic_menu_rotate,
        "charity" to android.R.drawable.ic_menu_share,
        "dots-horizontal" to android.R.drawable.ic_menu_more,
    )

    fun resolve(iconName: String?): Int {
        if (iconName.isNullOrBlank()) {
            return FALLBACK_ICON
        }
        return iconMap[iconName] ?: FALLBACK_ICON
    }
}
